"""Build the documented 0.7.0 reference package. Python 3 standard library only.

Run from any working directory. Reads the sibling tower_tank project and existing
Windows build; writes only inside ue_weapon_handoff and its sibling ZIP.
Does not edit or export the game. WAVs are generated by export_audio.gd first.
"""
from pathlib import Path
import csv
import datetime as dt
import hashlib
import json
import math
import re
import shutil
import wave
import zipfile

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT.parent
SOURCE = DOCS / "tower_tank"
EXE = DOCS / "builds/IronCitadel-Windows-x64/IronCitadel.exe"
ZIP = DOCS / "UE_Weapon_Handoff_IronCitadel_0.7.0.zip"
EXPECTED_EXE = "ce41ac023e580cd3b8f2e676702aa7ec98134c254ea3e8b58602fe6f7ccb820b"


def sha(path):
    h = hashlib.sha256()
    with path.open("rb") as f:
        for block in iter(lambda: f.read(1024 * 1024), b""):
            h.update(block)
    return h.hexdigest()


def write_json(relative, value):
    path = ROOT / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def write_csv(name, fields, rows):
    path = ROOT / "reference/curves" / name
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        for row in rows:
            writer.writerow({key: format(value, ".10g") if isinstance(value, float) else value
                             for key, value in row.items()})


assert 'config/version="0.7.0"' in (SOURCE / "project.godot").read_text(encoding="utf-8")
assert sha(EXE) == EXPECTED_EXE, "Executable changed; re-audit version before packaging"
src = {p.stem: p.read_text(encoding="utf-8") for p in (SOURCE / "scripts").glob("*.gd")}
source_checks = {}


def source_number(script, pattern, expected, label):
    match = re.search(pattern, src[script])
    assert match and float(match.group(1)) == expected, label
    source_checks[label] = True


for name, value in {"CAPACITY": 200, "FIRE_RATE": 20, "RELOAD_TIME": 7,
                    "BOLT_SPEED": 72, "BOLT_RANGE": 48, "DAMAGE": 8}.items():
    source_number("side_crossbows", rf"const {name} := ([\d.]+)", value, f"crossbow_{name}")
for name, value in {"aim_lag": .18, "turret_speed": 3.1, "reload_time": 1.65, "recoil_force": 1}.items():
    source_number("tank", rf"var {name} := ([\d.]+)", value, f"cannon_{name}")
for script, needle in [
    ("tank", "recoil * 110.0 - recoil_velocity * 17.0"),
    ("tank", "rock * 85.0 - rock_velocity * 10.0"),
    ("arena", "direction * 57.0"), ("arena", '"life": 2.1'),
    ("arena", "trauma - dt * 1.9"), ("arena", "aim_camera.size = zoom"),
    ("arena", "camera.size = zoom + zoom_punch * shake_strength"),
    ("side_crossbows", "arena.trauma = maxf(arena.trauma, 0.13)"),
    ("side_crossbows", "query.hit_from_inside = true"),
]:
    assert needle in src[script], (script, needle)
    source_checks[f"{script}: {needle}"] = True

params = {
    "schema_version": 1,
    "reference": {"game": "Iron Citadel", "version": "0.7.0", "engine": "Godot 4.7",
                  "spec_date": "2026-09-15", "physics_hz": 60, "viewport_px": [1440, 900],
                  "scope": "Reference values; proposed UE changes are in Markdown and are not silently applied here"},
    "units": {"distance": "metres unless suffix _cm", "time": "simulation seconds unless explicitly real/render",
              "angle": "radians unless suffix _deg", "godot_axes": "X right, Y up, -Z forward",
              "ue_position_cm": "100 * (-godot.z, godot.x, godot.y)",
              "ue_direction": "(-godot.z, godot.x, godot.y)",
              "ue_heading_yaw": "-GodotYaw * 180 / pi; transform bases for arbitrary rotations",
              "godot_light_energy": "not photometric UE units"},
    "cannon": {
        "input": {"button": "LMB", "hold_repeats": True, "buffer_s": .18,
                  "manual_reload": False, "finite_ammunition": False},
        "reload": {"duration_s": 1.65, "clock": "physics, paused by arena hitstop",
                   "events": [
                       {"name": "eject", "progress": .16, "nominal_s": .264},
                       {"name": "chamber", "progress": .43, "nominal_s": .7095, "barrel_v_add_mps": 2.7},
                       {"name": "lock", "progress": .86, "nominal_s": 1.419, "barrel_v_add_mps": -2.6,
                        "rock_pitch_v_add_radps": .1, "trauma_add": .15},
                       {"name": "ready", "progress": 1, "nominal_s": 1.65}],
                   "mechanical_impulses_scale_with_recoil_force": False},
        "projectile": {"speed_mps": 57, "speed_ue_cmps": 5700, "lifetime_s": 2.1,
                       "nominal_unobstructed_path_m": 119.7, "visual_radius_m": .14,
                       "collision": "segment ray each physics tick, not sphere sweep",
                       "mask_godot": 97, "channels": ["world", "fragile_props", "enemy"],
                       "gravity": 0, "inherits_actor_velocity": False, "homing": False,
                       "spread_rad": 0, "damage_direct": 110, "damage_splash": 60,
                       "splash_radius_m": 2.8, "direct_excluded_from_splash": True,
                       "enemy_sample_height_m": 1, "enemy_knockback_mps": 12,
                       "aoe_enemy_crew_los_check": False,
                       "muzzle_root_obstruction_test": False},
        "recoil": {"force_default": 1, "force_tuning_range": [.3, 1.8],
                   "barrel_initial_state_m": .21, "barrel_initial_v_mps": 16,
                   "barrel_k_per_s2": 110, "barrel_c_per_s": 17,
                   "integration": "v += (-k*x-c*v)*dt; x += v*dt; fixed 1/60s",
                   "visual_update": "shot state set after mesh update; first new pose after hitstop and next integration",
                   "rock_k_per_s2": 85, "rock_c_per_s": 10,
                   "rock_v_add": "(-Dlocal.z,Dlocal.x)*0.75*force rad/s",
                   "compression_v_add_mps": -1.4, "compression_k_per_s2": 110,
                   "compression_c_per_s": 14, "compression_limits_m": [-.2, .12],
                   "body_height_base_m": 1.18, "root_kick_mps": 1.8,
                   "root_kick_brake_mps2": 6.5, "ground_direction_renormalized": False},
        "shot_feedback": {"freeze_s": .045, "trauma_add": .8, "camera_kick_m": .6,
                          "ortho_height_punch_m": 1.3, "flash_alpha": .14,
                          "flash_rgb": [1, .84, .52]},
        "tuning": {"reload_range_s": [.65, 3], "aim_lag_range_s": [.04, .5]}
    },
    "crossbows": {
        "input": {"button": "RMB", "hold_repeats": True, "quick_tap_latched": True,
                  "tap_during_reload_discarded": True, "hold_resumes_after_reload": True},
        "capacity_shared": 200, "total_fire_rate_per_s": 20, "interval_s": .05,
        "per_side_fire_rate_per_s": 10, "first_side": "port / negative Godot local X",
        "alternate_across_bursts": True, "reload_s": 7, "manual_reload": False,
        "reload_events": [
            {"name": "start", "progress": 0, "nominal_s": 0},
            {"name": "magazine_lowest", "progress": .36, "nominal_s": 2.52},
            {"name": "chamber", "progress": .48, "nominal_s": 3.36},
            {"name": "magazine_home", "progress": .72, "nominal_s": 5.04},
            {"name": "lock", "progress": .90, "nominal_s": 6.3, "recoil_state_m": .10},
            {"name": "ready", "progress": 1, "nominal_s": 7}],
        "projectile": {"speed_mps": 72, "speed_ue_cmps": 7200, "range_m": 48,
                       "damage": 8, "enemy_knockback_mps": 1.3, "size_xyz_m": [.055, .055, .64],
                       "yaw_spread_uniform_rad": [-.009, .009], "pitch_spread_uniform_rad": [-.006, .006],
                       "mask_godot": 97, "collision": "segment ray + pivot-to-muzzle obstruction ray",
                       "hit_from_inside": True, "gravity": 0, "aoe": False,
                       "obstructed_shot_consumes_ammo": True},
        "mount": {"pivot_positions_godot_m": [[-1.43, .23, -.22], [1.43, .23, -.22]],
                  "muzzle_local_m": [0, .13, -1.25], "yaw_limits_rad": [-.25, .25],
                  "pitch_limits_rad": [-.9, .18], "aim_ease_per_s": 18,
                  "shot_recoil_state_m": .14, "recoil_return_mps": 2.4,
                  "feed_per_shot_rad": math.pi/6, "feed_ease_per_s": 20,
                  "arm_rotation_per_recoil_m": 1.8, "string_scale_z": "1 - recoil_m*1.8",
                  "magazine_home_y_m": -.23, "magazine_lower_m": .4,
                  "magazine_lower_cycle_fraction": .72,
                  "magazine_y": "-0.23-0.4*sin(pi*clamp(progress/0.72,0,1))",
                  "reload_extra_feed_rad": math.tau,
                  "visual_update": "recoil decays and applies before firing; 0.14 state gives 0.10 first visible at 60Hz"},
        "shot_feedback": {"rock_v_add_port_radps": [.022, -.025],
                          "rock_v_add_starboard_radps": [.022, .025], "trauma_floor": .13,
                          "freeze_s": 0, "camera_kick_m": 0, "zoom_punch_m": 0, "screen_flash": False},
        "hud": {"segments": 20, "low_color_below": 40, "warning_at_or_below": 40,
                "fire_pulse_decay_per_s": 9, "ready_pulse_decay_per_s": 1.5}
    },
    "aim": {"world_point_ease_per_s": 22, "world_ray_length_m": 180,
            "ground_plane_godot_y": 0, "mask_godot": 97, "source_camera": "before cosmetic impulse",
            "yaw_lag_s": .18, "yaw_max_speed_radps": 3.1,
            "yaw_max_speed_degps": math.degrees(3.1), "min_lag_s": .02,
            "pitch_limits_rad": [-.6, .15], "pitch_ease_per_s": 18,
            "cannon_preview_length_m": 85, "turret_world_pitch_roll_stabilized": True,
            "reticle_ease_per_s": 16, "reticle_max_speed_pxps": 1200,
            "reticle_alpha_ease_per_s": 20, "viewport_safe_margin_px": 20,
            "first_valid_reticle_snaps": True, "cursor_smoothing": False,
            "reticle_radius_px": 6, "cursor_reload_radius_px": 24, "cursor_reload_segments": 48,
            "connector_dots": 8, "connector_alpha": .3,
            "connector_distance_fade_px": [24, 64, 300, 420]},
    "camera": {"projection": "orthographic, keep vertical size",
               "base_vertical_size_m": 24, "base_ue_ortho_width_at_1440x900_cm": 3840,
               "ue_ortho_width_formula": "vertical_size_m*100*aspect_ratio",
               "zoom_range_m": [18, 42], "wheel_step_m": 1.5,
               "offset_godot_m": [24, 24, 24], "offset_ue_cm": [-2400, 2400, 2400],
               "focus_height_m": .75, "lead_factor": .13, "lead_max_m": 2.8,
               "follow_ease_per_real_s": 5, "strength_default": 1, "strength_tuning_range": [0, 1.7],
               "trauma_cap": 1, "trauma_decay_per_s": 1.9, "trauma_power": 2,
               "translation_amplitude_godot_xyz_m": [.44, .25, .35],
               "translation_angular_frequencies_radps": [103, 91, 117],
               "translation_functions": ["sin", "cos", "sin"],
               "roll_amplitude_rad": .011, "roll_angular_frequency_radps": 85,
               "global_phase_not_reset_on_shot": True,
               "kick_decay_per_s": 10, "zoom_decay_per_s": 7,
               "flash_decay_alpha_per_s": 4, "ready_decay_per_s": 2.3,
               "hit_confirm_decay_per_s": 3,
               "impact_trauma": {"normal": .38, "big": .65, "distance_scale_m": 45, "minimum_factor": .15},
               "decay_before_render_transform": True},
    "vfx": {"temporary_elements_cap": 420, "scorch_marks_cap": 45,
            "all_sizes_nominal_before_piece_scale": True,
            "piece_scale": "min(remaining_s*5,1)",
            "smoke_scale": "(0.35+1.8*age01)*min(remaining_s*3,1)",
            "ring_scale": "1+9*age01", "muzzle_ring_scale": "1+3.4*age01",
            "ring_alpha": "0.65*(1-age01)", "light_decay_s": .17,
            "cannon": {"light_energy_godot": 7, "light_range_m": 10,
                       "muzzle_core_radius_m": .58, "muzzle_core_life_s": .075,
                       "sparks_count": 16, "smoke_count": 9, "trail_width_m": .07, "trail_life_s": .13,
                       "ground_ring_radius_m": .55, "ground_ring_life_s": .32,
                       "normal_impact_debris": 20, "big_impact_debris": 34,
                       "big_impact_power": 1.6, "impact_smoke_count": 12},
            "crossbow": {"muzzle_box_xyz_m": [.16, .10, .34], "muzzle_life_s": .045,
                         "smoke_radius_m": .09, "smoke_life_s": .20,
                         "trail_width_m": .027, "trail_life_s": .065,
                         "hit_chips": 4, "hit_chip_xyz_m": [.055, .055, .13], "hit_life_s": .22}},
    "audio": {"format": "mono PCM16", "sample_rate_hz": 22050,
              "source_synthesis_rng_seed": 4107, "spatialized_in_reference": False,
              "gain_formula_db": "play_call_volume_db - 5",
              "pitch_multiplier_uniform": [.96, 1.04], "oneshot_overlap": True,
              "wav_contains_playback_gain_or_pitch": False,
              "events": {}},
}
audio_events = {
    "cannon_shot": ("fire", -5, 1), "cannon_eject": ("eject", -8, 1),
    "cannon_chamber": ("chamber", -7, 1), "cannon_lock": ("lock", -5, 1),
    "cannon_ready": ("ready", -9, 1), "normal_impact": ("impact", -11, 1),
    "barrel_impact": ("impact", -8, .85), "crossbow_port": ("repeater", -13, 1.04),
    "crossbow_starboard": ("repeater", -13, .94), "crossbow_hit": ("bolt_hit", -24, 1),
    "crossbow_reload_start": ("repeater_reload", -9, 1),
    "crossbow_chamber": ("chamber", -12, .70), "crossbow_lock": ("lock", -8, .75),
    "crossbow_ready": ("ready", -8, 1.35),
}
for event, (asset, gain, pitch) in audio_events.items():
    params["audio"]["events"][event] = {"wav": f"reference/audio/{asset}.wav",
                                          "gain_db": gain, "base_pitch": pitch}
write_json("parameters.json", params)

# Isolated recoil, initial state immediately after Shot. Mesh still at old pose.
step = 1 / 60
x, v, rock, rock_v, compression, compression_v, kick_v, kick_path = .21, 16, 0, .75, 0, -1.4, 1.8, 0
rows = []
for i in range(121):
    rows.append({"simulation_s_excluding_hitstop": i*step,
                 "barrel_state_m": x, "barrel_visible_m": 0 if i == 0 else x, "barrel_v_mps": v,
                 "rock_rad": rock, "rock_v_radps": rock_v,
                 "compression_m": compression, "compression_v_mps": compression_v,
                 "root_kick_speed_mps": kick_v, "root_kick_path_m": kick_path})
    v += (-110*x - 17*v)*step
    x += v*step
    rock_v += (-85*rock - 10*rock_v)*step
    rock += rock_v*step
    compression_v += (-110*compression - 14*compression_v)*step
    compression = max(-.2, min(.12, compression + compression_v*step))
    kick_path += kick_v*step  # root moves before deceleration in tank.tick
    kick_v = max(0, kick_v - 6.5*step)
write_csv("cannon_isolated_60hz.csv", list(rows[0]), rows)
peak = max(rows, key=lambda r: r["barrel_state_m"])
summary = {"cannon_barrel_peak_m": peak["barrel_state_m"],
           "cannon_barrel_peak_simulation_s": peak["simulation_s_excluding_hitstop"],
           "cannon_first_visible_pose_m": rows[1]["barrel_visible_m"],
           "rock_peak_deg": math.degrees(max(r["rock_rad"] for r in rows)),
           "compression_min_m": min(r["compression_m"] for r in rows),
           "root_discrete_unobstructed_travel_m": rows[-1]["root_kick_path_m"]}

rows = []
for i in range(181):
    t = i/120
    trauma = max(0, .8 - 1.9*t)
    rows.append({"render_game_s_since_shot": t, "trauma": trauma,
                 "world_x_amplitude_m": .44*trauma**2, "world_y_amplitude_m": .25*trauma**2,
                 "world_z_amplitude_m": .35*trauma**2, "roll_amplitude_rad": .011*trauma**2,
                 "directed_kick_m": .6*math.exp(-10*t),
                 "ortho_height_punch_m": 1.3*math.exp(-7*t),
                 "flash_alpha": max(0, .14 - 4*t)})
write_csv("camera_single_shot_envelopes_120hz.csv", list(rows[0]), rows)

rows = []
for i in range(13):
    recoil = max(0, .14 - 2.4*i*step)
    rows.append({"simulation_s": i*step, "recoil_state_m": recoil,
                 "rail_visible_m": 0 if i == 0 else recoil,
                 "arm_abs_rad": 0 if i == 0 else 1.8*recoil,
                 "string_z_scale": 1 if i == 0 else 1 - 1.8*recoil})
write_csv("crossbow_single_shot_60hz.csv", list(rows[0]), rows)
rows = []
for i in range(421):
    t = i*step
    p = min(t/7, 1)
    rows.append({"reload_simulation_s": t, "progress": p,
                 "magazine_y_m": -.23 - .4*math.sin(math.pi*min(p/.72, 1)),
                 "feed_target_extra_rad": p*math.tau,
                 "note": "chamber" if i == 202 else "lock" if i == 378 else "ready" if i == 420 else ""})
write_csv("crossbow_reload_targets_60hz.csv", list(rows[0]), rows)
write_json("reference/curves/derived_metrics.json", summary)

# Copy source snapshots and historical reports verbatim.
snapshot = ROOT / "reference/source"
snapshot.mkdir(parents=True, exist_ok=True)
copied = []
for path in sorted((SOURCE / "scripts").glob("*.gd")):
    target = snapshot / path.name
    shutil.copy2(path, target)
    assert sha(path) == sha(target)
    copied.append({"source_relative_to_project": f"scripts/{path.name}",
                   "package_path": target.relative_to(ROOT).as_posix(), "sha256": sha(target)})
shutil.copy2(SOURCE / "project.godot", snapshot / "project.godot.reference")
verification = ROOT / "reference/verification"
verification.mkdir(parents=True, exist_ok=True)
report_checks = {}
for name in ["aim_result.json", "crossbow_check.json", "battle_check.json", "crew_damage_check.json"]:
    path = SOURCE / "verification" / name
    shutil.copy2(path, verification / name)
    report = json.loads(path.read_text(encoding="utf-8"))
    checks = report.get("checks", report)
    report_checks[name] = {"copied_verbatim": sha(path) == sha(verification / name),
                           "checks_count": len(checks),
                           "all_checks_true": all(value is True for value in checks.values()),
                           "source_modified_utc": dt.datetime.fromtimestamp(path.stat().st_mtime, dt.timezone.utc).isoformat(),
                           "rerun_for_document_task": False}
for name in ["aim_regression.gd", "crossbow_regression.gd"]:
    shutil.copy2(SOURCE / "verification" / name, verification / name)

playable = ROOT / "playable"
playable.mkdir(exist_ok=True)
if not (playable / "IronCitadel.exe").exists() or sha(playable / "IronCitadel.exe") != EXPECTED_EXE:
    shutil.copy2(EXE, playable / "IronCitadel.exe")
assert sha(playable / "IronCitadel.exe") == EXPECTED_EXE
(playable / "PLAY_REFERENCE.cmd").write_bytes(
    b'@echo off\r\ncd /d "%~dp0"\r\nstart "" "%~dp0IronCitadel.exe" -- --reference\r\n')

audio_checks = {}
durations = {"fire": 1.5, "impact": 1.15, "eject": .5, "chamber": .58, "lock": .35,
             "ready": .4, "repeater": .1, "bolt_hit": .12, "repeater_reload": .9, "step": .42}
for name, duration in durations.items():
    with wave.open(str(ROOT / "reference/audio" / (name + ".wav")), "rb") as w:
        assert (w.getnchannels(), w.getsampwidth(), w.getframerate()) == (1, 2, 22050)
        actual = w.getnframes() / w.getframerate()
        assert abs(actual-duration) <= 1/22050 + 1e-8
        audio_checks[name] = {"sample_rate_hz": 22050, "channels": 1, "bits": 16, "duration_s": actual}
for event in params["audio"]["events"].values():
    assert (ROOT / event["wav"]).is_file()
for path in (ROOT / "reference/curves").glob("*.csv"):
    with path.open(encoding="utf-8") as f:
        for row in csv.DictReader(f):
            for key, value in row.items():
                if key != "note":
                    assert math.isfinite(float(value)), (path.name, key, value)

broken = []
link_count = 0
for path in ROOT.rglob("*.md"):
    for link in re.findall(r"\[[^\]]+\]\(([^)]+)\)", path.read_text(encoding="utf-8")):
        if link.startswith(("https://", "http://", "#")):
            continue
        link_count += 1
        target = link.split("#")[0]
        if (path.parent / target).resolve() in (ROOT / "MANIFEST.json", ROOT / "PACKAGE_CHECK.json"):
            continue  # generated below
        if not (path.parent / target).exists():
            broken.append((path.relative_to(ROOT).as_posix(), link))
assert not broken, broken

check = {"passed": True, "scope": "Artifact integrity; not a fresh gameplay run or a UE acceptance result",
         "source_value_checks": source_checks, "source_copy_count": len(copied),
         "markdown_relative_links_checked": link_count, "broken_markdown_relative_links": broken,
         "csv_values_finite": True, "audio_checks": audio_checks,
         "historical_godot_reports": report_checks,
         "playable_sha256": EXPECTED_EXE, "derived_curve_metrics": summary}
write_json("PACKAGE_CHECK.json", check)

def included(path):
    return path.is_file() and path.suffix not in (".log", ".pyc") and "__pycache__" not in path.parts

files = sorted(p for p in ROOT.rglob("*") if included(p) and p.name != "MANIFEST.json")
manifest = {"package": "Epic Battle Mages UE weapon handoff", "revision": 1,
            "reference_version": "0.7.0", "created_utc": dt.datetime.now(dt.timezone.utc).isoformat(),
            "source_project": "docs/tower_tank", "source_code_modified_by_document_task": False,
            "playable_origin": "docs/builds/IronCitadel-Windows-x64/IronCitadel.exe",
            "playable_sha256": EXPECTED_EXE, "source_snapshot": copied,
            "notes": ["WAVs exported from sound.gd bank via Godot; no mix gain or pitch baked in",
                      "CSVs calculated from source formulas, not captured gameplay telemetry",
                      "Historical Godot QA reports copied verbatim; no UE implementation tested",
                      "Manifest intentionally does not hash itself"],
            "files": [{"path": p.relative_to(ROOT).as_posix(), "bytes": p.stat().st_size,
                       "sha256": sha(p)} for p in files]}
write_json("MANIFEST.json", manifest)
files.append(ROOT / "MANIFEST.json")
with zipfile.ZipFile(ZIP, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=6) as archive:
    for path in files:
        archive.write(path, "ue_weapon_handoff/" + path.relative_to(ROOT).as_posix())
with zipfile.ZipFile(ZIP) as archive:
    assert archive.testzip() is None
    for entry in manifest["files"]:
        h = hashlib.sha256()
        with archive.open("ue_weapon_handoff/" + entry["path"]) as f:
            for block in iter(lambda: f.read(1024*1024), b""):
                h.update(block)
        assert h.hexdigest() == entry["sha256"]
print(json.dumps({"passed": True, "files": len(files), "zip": str(ZIP), "zip_bytes": ZIP.stat().st_size,
                  "zip_sha256": sha(ZIP), "metrics": summary}, ensure_ascii=True, indent=2))
